### ISSUE TITLE
Support AoT Compilation

### ISSUE THREAD

**Issue by shaneog** [cesarrew/ng2-currency-mask#1]
Would be great to support [Ahead-of-Time](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html) (AoT) compilation.

**Comment by cesarrew** [comment]
Right, I will check this out.

**Comment by cesarrew** [comment]
@shaneog, the new 1.0.4 version supports AOT now.

**Comment by shaneog** [comment]
Thank you!

**Comment by lfv89** [comment]
@shaneog @cesarrew Thanks for your work! Now the AOT doesn't brake, but when I open the app though nothing happens and this what the chrome's console tells me:

```
Uncaught Error: Module build failed: Error: /Users/foo/Projects/bar/node_modules/ng2-currency-mask/src/currency-mask.directive.d.ts (1,1): Cannot find type definition file for 'core-js'.)(…)
```

Do you know what this could be?

Thanks.

**Comment by cesarrew** [comment]
I was able to test the component using this repo: https://github.com/qdouble/angular2webpack2-starter.git.

Check if you are using typescript 2.0.3 or higher and using "@types/core-js": "^0.9.34" in your devDependencies instead of typings.json.

**Comment by lfv89** [comment]
@cesarrew 

Our project is based on angular-cli and apparently there is an unresolved issue with adding `@types/core-js` to it: https://github.com/angular/angular-cli/issues/1908

**Comment by lfv89** [comment]
Also: http://stackoverflow.com/questions/38814049/howto-import-core-js-map-into-angular-cli-webpack-generated-application

**Comment by lfv89** [comment]
Fixed it.

A change in the `tsconfig.json` file is necessary for those who are using `angular-cli`:

```
// before
"lib": ["es6", "dom"],
```

```
// after
"lib": ["es5", "dom"],
```

**Comment by cesarrew** [comment]
Thanks for the feedback @lfv89.

**Comment by cesarrew** [comment]
Version 1.0.6 fixed the problem and no more changes in tsconfig.json is needed.
