### ISSUE TITLE
mask is not set by updating value via code

### ISSUE THREAD

**Issue by dwegzero** [cesarrew/ng2-currency-mask#10]
If you change the ngModel value in code the mask is not assigned

**Comment by cesarrew** [comment]
I tried to reproduce this situation and the problem didn't occur. Could you provice a code sample?

**Comment by dwegzero** [comment]
I'm sorry. After a closer look I have realized that the binding was set to [value] not to [ngModel] of the input. Bind the value to ngModel did job.
