### ISSUE TITLE
Not working with lazy loading

### ISSUE THREAD

**Issue by ErickXavier** [cesarrew/ng2-currency-mask#102]
For some reason this is not working with lazy loading. The lazy loading technique I'm using is this one:
https://angular.io/guide/lazy-loading-ngmodules

I'm loading the directive as requested on the README.md but simply doesn't works. Doesn't generates any kind of error though.

Btw, I'm using the material.angular.io components too. Is this ready for them?

**Comment by cesarrew** [comment]
I couldn't reproduce the problem. Working as expected in my tests.
