### ISSUE TITLE
can't copy or paste values in firefox 61.0.1

### ISSUE THREAD

**Issue by lourencomcviana** [cesarrew/ng2-currency-mask#118]
when trying to copy something from a input with ng2-currency-mask the selected content get erased, but not copied.

pasting seens to not work also.

I can make it work by selecting the content, right clicking and them selecting copy or paste from the list.

**Comment by psenechal** [comment]
I am also seeing this issue in Firefox 60.0.2. I do not see the issue in Chrome.

**Comment by luisfwermann** [comment]
Hello guys, same issue here https://github.com/cesarrew/ng2-currency-mask/issues/99
It seems that someone has already resolved the problem... it just needs to be added to the master branch...
@cesarrew  Can you do that for us?

**Comment by oalencar** [comment]
+1

**Comment by psenechal** [comment]
Is there an estimated timeline on an updated release with this fix? We would love to continue using this package, but the testing team is getting anxious. Thanks =)

**Comment by EmaGht** [comment]
Fix reference:
https://github.com/cesarrew/ng2-currency-mask/pull/100

**Comment by hitpopdimestop** [comment]
Hello! Are there any updates about this issue?

**Comment by cesarrew** [comment]
It's working in Firefox 95.
