### ISSUE TITLE
Can we declare default options?

### ISSUE THREAD

**Issue by rgiosa** [cesarrew/ng2-currency-mask#13]
If so, how can we do it?

Thank you!

**Comment by cesarrew** [comment]
Yes, you can. Check the README.md for details.
[](https://github.com/cesarrew/ng2-currency-mask/blob/master/README.md)

**Comment by rgiosa** [comment]
Sorry, I meant globally.

**Comment by cesarrew** [comment]
It's not possible. What I do in similar situation is create a service with global objects ("options" in this case) and inject it in every necessary component.

**Comment by rgiosa** [comment]
Ok, thank you!
