### ISSUE TITLE
Feature request - Add support for forms

### ISSUE THREAD

**Issue by codeunifier** [cesarrew/ng2-currency-mask#130]
I'm having issues using the currencyMask directive with a form control. Seems to only work with ngModel, which is great, but it would be awesome to also have support for forms.

**Comment by cesarrew** [comment]
Hello. I suggest you check the following example that uses the library with reactive forms and template driven as well.

https://github.com/cesarrew/ng2-currency-mask/tree/master/projects/library-test.

**Comment by cesarrew** [comment]
Another option: https://stackblitz.com/edit/angular-ivy-bpn8by
