### ISSUE TITLE
Does ng2-currency-mask implement Internationalization?

### ISSUE THREAD

**Issue by mwolfhoffman** [cesarrew/ng2-currency-mask#131]
I'm in the US and the example in the README is in USD. I'm wondering what the internationalization implementation is. Is ng2-currency-mask picking up on locale or is it only using USD? 

I see the options in the CurrencyMaskConfig but is there a way to support other currencies?

**Comment by cesarrew** [comment]
You can change the currency symbol (prefix / suffix), decimal and thousands separator. It's not picking up the current locale.
