### ISSUE TITLE
Doesn't work in Angular 8 when import in AppModule.

### ISSUE THREAD

**Issue by ericferreira1992** [cesarrew/ng2-currency-mask#133]
I'm migrating my application to version 8 of Angular, and I'm having problems when run my application. The application works fine when remove the CurrencyMaskModule.
The Angular return the following error:
![image](https://user-images.githubusercontent.com/12420366/63541498-9b6a2580-c4f4-11e9-8802-70d042c3a7e5.png)

But I mapped the error when the script of `core.js` is running, catching which module has trouble run. (See the return down below)
![image](https://user-images.githubusercontent.com/12420366/63542510-ebe28280-c4f6-11e9-8d6a-9f7739407fc6.png)

I don't know exactly the reason of the problem, but it say that error is in this part of code from `core.js`:
`if (ngModuleType.ngModuleDef.id !== null) {`
Where ngModuleType.**ngModuleDef** is `undefined`.

I would very much like you to help me with this as I don't want to stop using your package. Thanks!

**Comment by ozzpy** [comment]
for me work perfec, can you show your code, you are report the core.js and not how you implement your code

**Comment by ericferreira1992** [comment]
I just importing the module in my project. But I saw that many peoples who migrated their projects to version 8 of Angular had many problems when to use the Ivy, later I disable Ivy and the package work correctly. You can close this issue, this was my mistake due to the version upgrade.

**Comment by eliteproxy7** [comment]
how can we make sure when we upgrade from angular 7 to 8 and want to run IVY that this error is resolved?
