### ISSUE TITLE
Problem mask with devices android in chrome

### ISSUE THREAD

**Issue by Juliojss** [cesarrew/ng2-currency-mask#134]
I encountered a problem with masking on android devices in chrome 76. When erasing the value, it does not add the mask again. An alternative was to apply nullable false to mask settings.

**Comment by ivofernandes** [comment]
The problem is with the event target isn't?

**Comment by ivofernandes** [comment]
Check if this fixes your bug :)
https://github.com/cesarrew/ng2-currency-mask/pull/150

**Comment by cesarrew** [comment]
Fixed in version 13.0.3.
