### ISSUE TITLE
Any plan to support Angular 8 with ivy enabled?

### ISSUE THREAD

**Issue by yuchaosydney** [cesarrew/ng2-currency-mask#138]
My project has ng2-currency-mask as a dependency. Today I tried to build my app with ivy enabled and get following error

`ERROR in ../node_modules/ng2-currency-mask/src/currency-mask.module.d.ts:1:22 - error TS-996002: Appears in the NgModule.imports of GeneralSettingsModule, but could not be resolved to an NgModule class`

Do we have any plan to support ivy as I think it will be a very cool feature coming out of box in Angular 9

**Comment by andrejm7** [comment]
we need this .. any predictions?

**Comment by javed23** [comment]
i am also getting the same error with ivy enabled in angular8+

**Comment by andrejm7** [comment]
@javed23 use ngx-currency

**Comment by cesarrew** [comment]
Please upgrade to version 9.0.0.
