### ISSUE TITLE
Mouse Focus Left Point

### ISSUE THREAD

**Issue by ethemsulan** [cesarrew/ng2-currency-mask#14]
How can i set mouse focus to left of decimal point? when i press Tab and focus to input i want to focus to **0{mouse_focus_here}.00**
For now mouse focus 0.00{here}. i do not want to focus like that.

**Comment by cesarrew** [comment]
What version are you using? You can put the cursor at the left side of decimal separator clicking at the desired location. Using only the tab key it's not possible.
