### ISSUE TITLE
Cannot find module 'ng2-currency-mask'.

### ISSUE THREAD

**Issue by hugo-feijo** [cesarrew/ng2-currency-mask#140]
The new Version 9.0.1 is present a error of import. The following mensagem appear when try to Import:
![Captura de Tela 2020-03-31 às 09 42 11](https://user-images.githubusercontent.com/53494832/78033103-f211ca80-7333-11ea-93f0-00ddba142da7.png)

When i Roll Back to the version 9.0.0 everything was fine.

**Comment by cesarrew** [comment]
Please use the new version 9.0.2 to fix this.
