### ISSUE TITLE
The directive only works with input tag?

### ISSUE THREAD

**Issue by NathanAlcantara** [cesarrew/ng2-currency-mask#141]
I tried to use in a span tag just to display a data but don't worked.

My question is, this is the expected behavior and is not implemented or i'm doing something wrong? If is the first one, it will be soon?

I'm trying do use this way:

```
<span
    currencyMask
    [options]="maskOptions"
>
     {{ value }}
</span>
```

i tried put `[ngModel]="value"` and no success too

**Comment by cesarrew** [comment]
Yes, the directive only works in inputs.
