### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by deprecat3d** [cesarrew/ng2-currency-mask#147]
just following documentation (not globally example)

**Comment by EpicVoyage** [comment]
Did you add `NgxCurrencyModule` to your Angular module imports?

**Comment by gleisonkz** [comment]
same problem here, and I already import the CurrencyModule

**Comment by cesarrew** [comment]
Hello. I suggest you check the following example that uses the library with reactive forms and template driven as well.

https://github.com/cesarrew/ng2-currency-mask/tree/master/projects/library-test.

**Comment by cesarrew** [comment]
Another option: https://stackblitz.com/edit/angular-ivy-bpn8by

**Comment by AleffBruno** [comment]
1.
![image](https://github.com/cesarrew/ng2-currency-mask/assets/11706356/088d9356-0ff9-420f-8ddb-dc4e75c4b87f)

2.
![image](https://github.com/cesarrew/ng2-currency-mask/assets/11706356/959cda08-868c-4e12-835c-6598c839e5b3)

3.
        <input matInput [(ngModel)]="value" (keyup)="parcelIonChange($event)" currencyMask [options]="{ prefix: '', thousands: '.', decimal: ',' }">

I just follow the steps that 'cesarrew' ( the guy above ) post
