### ISSUE TITLE
Type over Input behavior is disabled

### ISSUE THREAD

**Issue by bburttram** [cesarrew/ng2-currency-mask#15]
If I select all or part of an existing value and try to replace it by typing "over" the selected text, I'm unable to do so (including using the DELETE key).

**Comment by cesarrew** [comment]
It's a expected behavior. It was implemented this way to avoid some problems. You can paste or copy a content using the context menu.

**Comment by bburttram** [comment]
Ok, roger that and thank you.  Out of curiosity, would you mind commenting on the problems you encountered?

**Comment by igordeoliveirasa** [comment]
Oh no man, everybody really needs to type over. Is there any option to disable that?

**Comment by cesarrew** [comment]
There isn't an option to disable that. What are the exactly actions do you usually take that are being limited by this constraint?

**Comment by phsilva** [comment]
@cesarrew having the same issue here.

For me, breaking the natural flow of pressing TAB in one field and start typing in the next one is unacceptable in my application.

Can you comment on the issues you had and see if we can add a way to disable it if necessary?

**Comment by bojanfbm** [comment]
Any news on this issue? Can we expect anything?

**Comment by bburttram** [comment]
One use case would be any application that has tabular data entry where the user would expect to be able to type immediately upon the control receiving focus, regardless of if an existing value were present.

**Comment by cesarrew** [comment]
Right. I will fix this as soon as possible.

**Comment by cesarrew** [comment]
A new version was released (2.0.1 and 4.0.1) allowing delete and add numbers in a full selected input. @bburttram @igordeoliveirasa @phsilva @bojanfbm @musatov, please check if it is the desired behavior.

**Comment by bburttram** [comment]
The only thing I noticed is that selecting an existing value and removing it with the delete key leaves a $0.00 value, which prevents returning the control to it's original value of null leaves a dirty validator, but that may be a separate issue.  The typeover behavior seems fixed and otherwise behaves as I would expect, thank you!

**Comment by drsatan1** [comment]
Nice! Definitely using this now.

**Comment by phsilva** [comment]
@cesarrew great work, thanks.

**Comment by musatov** [comment]
@cesarrew thank you!
