### ISSUE TITLE
ng2-currency-mask incompatible with Angular 11

### ISSUE THREAD

**Issue by suporte03** [cesarrew/ng2-currency-mask#151]
Hi there.
Angular 11 has just been released.
As a good Angular developer, I'm starting to migrate my project to the version 11.
Sadly, the only thing that happened is that the ng2-currency-mask library is not compatible with this version.

This is the screen when trying to update using: "ng update @angular/cli @angular/core @angular/compiler-cli":
![image](https://user-images.githubusercontent.com/56367197/101061843-b472da80-356f-11eb-825e-6dd3acecbe16.png)

After using the --force parameter, I updated Angular, but the project does not compile:
![image](https://user-images.githubusercontent.com/56367197/101061385-357da200-356f-11eb-9e4b-fa5dd90a4c9b.png)

Anything I can do for this library to work on this version?

**Comment by michaelwestphal** [comment]
I utilize this library in an Angular 11 application successfully. Running [`ngcc`](https://angular.io/guide/glossary#ngcc) appears to be the crucial step. 

That said, I would love to see this library updated too! Until then I'll have to continue to use the `--force` flag with `ng update`.

**Comment by cesarrew** [comment]
Upgraded to Angular 11.
