### ISSUE TITLE
mask doesn't work when inside ReactiveForms formArray

### ISSUE THREAD

**Issue by felipesantos1504** [cesarrew/ng2-currency-mask#152]
* [Stackblitz]((https://imask-currency-vu8myy.stackblitz.io)) - Issue happening

The title explains all, above have a stackblitz with the issue.

**Comment by DionatanGG** [comment]
The stackblitz link is not working.
About the problem, you can use a ngModel inside a reactive forms, just use the [ngModelOptions]="{ standalone: true }" option.

**Comment by cesarrew** [comment]
Hello. The following example uses the library with reactive forms and formArray.

https://github.com/cesarrew/ng2-currency-mask/tree/master/projects/library-test

**Comment by cesarrew** [comment]
Another option: https://stackblitz.com/edit/angular-ivy-bpn8by
