### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by hamidpp** [cesarrew/ng2-currency-mask#158]
ERROR in No suitable injection token for parameter 'elementRef' of class 'CurrencyMaskDirective'.
no type or decorator

**Comment by williamxsp** [comment]
Do you have any sample code?

What angular version are you using?

**Comment by cesarrew** [comment]
Hello. I suggest you check the following example that uses the library with reactive forms and template driven as well.

https://github.com/cesarrew/ng2-currency-mask/tree/master/projects/library-test.

**Comment by cesarrew** [comment]
Another option: https://stackblitz.com/edit/angular-ivy-bpn8by
