### ISSUE TITLE
TypeError: Cannot set property 'textAlign' of undefined

### ISSUE THREAD

**Issue by spottedmahn** [cesarrew/ng2-currency-mask#16]
Hello - I receiving the following error: "TypeError: Cannot set property 'textAlign' of undefined".  I only see this error after adding the 'currencyMask' directive to my input box.  I'm not sure where to start debugging this... please advise.  Thanks!

**Comment by spottedmahn** [comment]
As an experiment, I commented out the following in currency-mask.directive.js and it worked!  Obviously this is not a long term fix but maybe it helps diagnosis the issue.

    CurrencyMaskDirective.prototype.ngAfterViewInit = function () {
        //this.elementRef.nativeElement.style.textAlign = this.options.align;
    };

**Comment by cesarrew** [comment]
Could you provide a code sample showing how you are using the directive?

**Comment by spottedmahn** [comment]
Sure thing.

![image](https://cloud.githubusercontent.com/assets/14079228/24364439/c7e938e4-12e0-11e7-8ba0-3c675869fa52.png)

![image](https://cloud.githubusercontent.com/assets/14079228/24364542/1325df1a-12e1-11e7-8f81-09ca7c9b55c1.png)

![image](https://cloud.githubusercontent.com/assets/14079228/24364411/b3d97558-12e0-11e7-8ec4-483f24cf2eba.png)

**Comment by cesarrew** [comment]
Could you try the new version 1.5.1 to check if the problem continues?

**Comment by spottedmahn** [comment]
it is working as expected with: "ng2-currency-mask": "^2.0.1"!

**Comment by ireade** [comment]
Hi @cesarrew ! Thanks for creating this. I'm getting this error as well (even when I use the version specified by @spottedmahn ). 

I believe that this is due to my using Angular Universal. I found that, if I only displayed the input when the Browser version of the application is active, I don't get any errors.

**Comment by cesarrew** [comment]
@ireade, Please try the newest version of this directive. You can check all releases at https://github.com/cesarrew/ng2-currency-mask/releases. You should use the version 2.x.x for Angular 2.x.x applications and the version 4.x.x for Angular 4.x.x applications.

**Comment by ireade** [comment]
@cesarrew I've tried the newest versions. I'm using Angular 2.2.3 so I used version 2.2.0 of the directive. I also tried the latest 4.x.x version, and the 2.0.1 version that spottedmahn tried.
