### ISSUE TITLE
Cannot find module 'ng2-currency-mask' in Angular 12

### ISSUE THREAD

**Issue by gleisonkz** [cesarrew/ng2-currency-mask#161]
Hi I update my Angular version to 12 and also the ngs-currency-mask library, but now I'm getting an error when I try to import the library, What Am I doing wrong?

![image](https://user-images.githubusercontent.com/48810597/130259651-c7d4c4a9-6398-465f-b020-09ad8df1170b.png)

Angular CLI: 12.2.2
Node: 12.14.1
Package Manager: npm 7.20.5
OS: win32 x64

Angular: 12.2.2
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@angular/cdk                    10.2.7
@angular/material               10.2.7
@schematics/angular             12.2.2
rxjs                            6.6.7
typescript                      4.3.5

**Comment by cesarrew** [comment]
Fixed in version 12.0.3.
