### ISSUE TITLE
Support for Angular 4

### ISSUE THREAD

**Issue by jvbianchi** [cesarrew/ng2-currency-mask#17]
Does this library has support for Angular 4?

**Comment by JoaoPauloCMarra** [comment]
Hi,

I jsut did an upgrade to 4, and I have the following error report:

`ng2-currency-mask/src/currency-mask.directive.d.ts (10,21): Generic type 'KeyValueDiffer<K, V>' requires 2 type argument(s).`

![image](https://cloud.githubusercontent.com/assets/976151/24295728/ee3f714c-107a-11e7-8326-c636b651aeac.png)

I've just commented that, and It works, but hope you guys fix it :)

**Comment by jvbianchi** [comment]
I got the same error

**Comment by cesarrew** [comment]
I'll fix this soon. Thanks.

**Comment by cesarrew** [comment]
A new version was released supporting Angular 4. Please verify if the error still shows up.

**Comment by RodolfoSilva** [comment]
@cesarrew I got the same error with the last version 1.5.1

```
/node_modules/ng2-currency-mask/src/currency-mask.directive.d.ts (10,21): Type 'KeyValueDiffer' is not gener
ic.)
```

**Comment by RodolfoSilva** [comment]
It's not compatible with angular 2.4.*
