### ISSUE TITLE
Support for Ionic 2

### ISSUE THREAD

**Issue by niconaso** [cesarrew/ng2-currency-mask#18]
Hi! Excellent component. Do you plan to support Ionic 2?

**Comment by cesarrew** [comment]
Thanks. Yes, I plan.

**Comment by marcoskichel** [comment]
Any release date?

**Comment by sneurlax** [comment]
It turns out that this is *just a bit* more difficult than changing


    { type: core_1.Directive, args: [{
                selector: "input[currencyMask]",
                providers: [exports.CURRENCYMASKDIRECTIVE_VALUE_ACCESSOR]
            },] },

to


    { type: core_1.Directive, args: [{
                selector: "ion-input[currencyMask]",
                providers: [exports.CURRENCYMASKDIRECTIVE_VALUE_ACCESSOR]
            },] },

**Comment by cesarrew** [comment]
I've changed the directive's selector, but I'm struggling to have time to test this directive in Ionic. Could someone do this test with the new version?

**Comment by Pernett98** [comment]
Hi! not works.
console output is: Cannot read property 'createRange' of undefined

**Comment by iowaz** [comment]
Hello.

I has the "Cannot read property 'createRange' of undefined" error, even if I use just a input with type=number.

It's correct to assume that type='number' can't be used with masks?

**Comment by isrmicha** [comment]
most of the masks i see use type="text"

**Comment by cesarrew** [comment]
There is a new section in README.md called 'Quick fixes' with some tips to use this directive with Ionic. If problems persist, please reopen the issue.

**Comment by Sampath-Lokuge** [comment]
@cesarrew Can you tell me what is `index` here? Do we need to define that on `ts` file? 

` <input currencyMask type="tel" [(ngModel)]="value" [id]="'yourInputId' + index" (focus)="scrollTo(index)" />`

I cannot click the input box. Do I need to use `ion-input` instead?
