### ISSUE TITLE
Max length option

### ISSUE THREAD

**Issue by alexandredavi** [cesarrew/ng2-currency-mask#19]
Is it possible to have a max length option?

**Comment by vinodbirajdar** [comment]
Max length doesn't work with this.

**Comment by cesarrew** [comment]
@alexandredavi and @vinodbirajdar. The maxlength html input attribute worked as expected in my tests.

**Comment by calebeaires** [comment]
@cesarrew Is there any way to precision make max decimal lenth, it seans that the mask just make min length

**Comment by cesarrew** [comment]
Minimum and maximum values validation are now available in version 5.3.0.

**Comment by raDiesle** [comment]
I am looking forward for max character length masking. ( not max validation)
Would be nice to add it as option parameter.
