### ISSUE TITLE
Type 'KeyValueDiffer' is not generic.

### ISSUE THREAD

**Issue by daddyschmack** [cesarrew/ng2-currency-mask#20]
Hi Guys,

How do I deal with this error?  
ap-angular-portal/node_modules/ng2-currency-mask/src/currency-mask.directive.d.ts (10,21): Type 'KeyValueDiffer' is not generic.

@angular/cli: 1.0.0
node: 7.7.4
os: darwin x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/material: 2.0.0-beta.2
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

**Comment by norris1976** [comment]
Same issue for me

**Comment by cesarrew** [comment]
You should use the version 2.x.x for Angular 2.x.x applications and the version 4.x.x for Angular 4.x.x applications.

**Comment by norris1976** [comment]
Specifying the version (v2) worked for me. Thanks.

**Comment by amantur** [comment]
@cesarrew what should be changed? I think all the stuff in `package.json` is `@v2`

**Comment by jcezarms** [comment]
This same error happened to me recently in a Jenkins build process.
Managed it by putting `ng2-currency-mask@4.0.0` as a dependency, matching the versions of all `@angular` dependencies in my project.
