### ISSUE TITLE
KeyValueDiffer is not generic

### ISSUE THREAD

**Issue by drsatan1** [cesarrew/ng2-currency-mask#21]
I get this error when compiling:

/node_modules/ng2-currency-mask/src/currency-mask.directive.d.ts

Typescript Error
Type 'KeyValueDiffer' is not generic.

```
inputHandler: InputHandler;
keyValueDiffer: KeyValueDiffer<any, any>;
optionsTemplate: {
```

**Comment by cesarrew** [comment]
You should use the version 2.x.x for Angular 2.x.x applications and the version 4.x.x for Angular 4.x.x applications. The latest releases are 2.0.1 and 4.0.1.

**Comment by MehranJanfeshan** [comment]
worked for me, thanks, I just updated my package.json to :
 "ng2-currency-mask": "^2.0.0",
