### ISSUE TITLE
Flexible precision

### ISSUE THREAD

**Issue by tomkosse** [cesarrew/ng2-currency-mask#22]
Currently, it's not possible to have the user enter between 0 and 2 decimals. We're using this in a finance context, where often we specify bigger numbers like EUR 25.000. In these cases, it's not user friendly to require the user to type 2500000.

Would it be possible to add some flexibility in this regard?

**Comment by cesarrew** [comment]
If I understood correctly, you want to use dot to separate the decimal part. It's not possible, but if you do not need using decimals, you can set the precision to 0 and have the desired behavior.

**Comment by tomkosse** [comment]
No, i would be content to use any character as the decimal delimiter. What i would like to be able to do is allow the following inputs:

25,000 (25 thousand)
25,000.00 (25 thousand)
26,000,24 (25 thousand and 24 cents).

In our cases, supplying cents is added precision which is not always mandatory.

**Comment by cesarrew** [comment]
This would bring too much changes and I can't do it right now. I will avaliate in the future.

**Comment by dhniels** [comment]
@cesarrew this feature would be necessary in my application as inputting data in tables or several inputs at a time becomes very tedious, requiring extra keystrokes for decimal values. seems like this is the same issue as https://github.com/cesarrew/ng2-currency-mask/issues/61
