### ISSUE TITLE
Trying to delete via backspace not working when right after thousands / decimal devider

### ISSUE THREAD

**Issue by dk5koppe** [cesarrew/ng2-currency-mask#25]
Hi,
awesome work - thanks a lot.

I stumbled over an issue with deleting via backspace when the cursor stands right after the devider.
I think it's because of the live formating - you always delete the divider and insert it right again after each keystroke.

Do you think, you could fix that?

Many thanks!

**Comment by cROSs116** [comment]
Created a Pull request with the fix for the author: https://github.com/cesarrew/ng2-currency-mask/pull/85

**Comment by wagedomain** [comment]
+1

Starting at the left-most number of a number with commas and hitting delete removes numbers up until the comma, then moves the cursor to the end of the number.

**Comment by cesarrew** [comment]
Fixed in latest version.
