### ISSUE TITLE
[question] global options

### ISSUE THREAD

**Issue by afgallo** [cesarrew/ng2-currency-mask#28]
Hi @cesarrew, thanks for this, saved my day!

How can we set global options for an entire app instead of going with the below config for each and every input?

```
[options]="{ prefix: 'R$ ', thousands: '.', decimal: ','}"
```

**Comment by cesarrew** [comment]
It's not possible. What I do in similar situation is create a service with global objects ("options" in this case) and inject it in every necessary component.
