### ISSUE TITLE
Type over partly selected Input

### ISSUE THREAD

**Issue by jschmuecking** [cesarrew/ng2-currency-mask#29]
Hi @cesarrew, thanks for the great plugin,

This is probably related to Issue #15. When we select part of the current input to replace it nothing happens on key Inputs. We are forced to delete the respective parts without selecting them and enter the new values.

For us this is relevant when the user wants to make small changes to his input but doesnt want to reenter his whole input.

**Comment by andreluisce** [comment]
Hello, Does anyone know a solution for this bug? I am facing the same problem.

**Comment by brandon-a-hay** [comment]
I'm seeing the same problem, too.

**Comment by brandon-a-hay** [comment]
Looks like the resolution for [#15](https://github.com/cesarrew/ng2-currency-mask/issues/15) was just to allow editing the value when you select the entire length of the input. @cesarrew says there are some issues that ran in to when allowing users to partially select. Would be nice to know what those were. I made a very simple change in `input.handler.js` on the `handleKeypress` function in the `default` case and now I get the desired behavior and don't notice any problems as of yet:

`default:
                if (this.inputService.canInputMoreNumbers) {
                    var selectionRangeLength = Math.abs(this.inputService.inputSelection.selectionEnd - this.inputService.inputSelection.selectionStart);
                    if (selectionRangeLength == this.inputService.rawValue.length) {
                        this.setValue(0);
                    }
                    this.inputService.addNumber(keyCode);
                }`

**Comment by cesarrew** [comment]
@brandon-a-hay I'm not sure what are these issues anymore, but I think that it's related with using this directive in Chrome for Android. I have implemented your suggestion, but it only works if your are typing numbers over the selected text. You still can't delete when there is partial text selected. Any problems, let me know.
