### ISSUE TITLE
Doesn't seem to work on Android

### ISSUE THREAD

**Issue by shaneog** [cesarrew/ng2-currency-mask#3]
I'm using this component (thank you!) but it doesn't seem to work on Chrome on Android. (Android 6)

When the user types the mask is not overwritten, and the validation fails regardless of what the user types.

_I'm using AoT compilation if that makes any difference._

**Comment by cesarrew** [comment]
Thanks, I will check it out.

**Comment by cesarrew** [comment]
It's not working on Android indeed. I will fix this soon.

**Comment by cesarrew** [comment]
The issue has been fixed in 1.1.0 version. Could you verify it?

**Comment by shaneog** [comment]
It works now. Thank you very much! 👍
