### ISSUE TITLE
On clearing field the input defaults to '0'

### ISSUE THREAD

**Issue by FaraKahir2** [cesarrew/ng2-currency-mask#30]
On clearing an input field I would like the text to be blank rather than default to '0' Ideally, I would like to be able to configure this in the options settings. At the moment even when I delete the 0, if still says zero.

**Comment by ebosantos** [comment]
it'd be a great improvement.

**Comment by jans-y** [comment]
In the /src/input.service.js on line 20 add to the top of the function:

>InputService.prototype.applyMask = function (isNumber, rawValue) {
 if(rawValue == '') {  // <-- checking if you cleared it.
     return ''; // <-- this is returning empty string to have it blank
 } else {
    ......original code .....
 }
}

**Comment by stieler-it** [comment]
The fix by @jans-y does not seem to work in all cases. I can only clear the value by leaving the field, focusing it again and then pressing space. It does not even work with backspace / delete. (Tested in Chrome)

**Comment by cesarrew** [comment]
I will prioritize this issue and do it asap.

**Comment by cesarrew** [comment]
Fixed in version 4.4.0.

**Comment by ysfjwd** [comment]
Hey @cesarrew. We should probably have an option, allowBlank. The way before 649cd8734 was how we intended we were using it. makes sense?

//ysf

**Comment by AndrewEckart** [comment]
@cesarrew would it be possible to add an option for the value the field should be reset to if it is cleared? The default could remain null, but it'd be nice to be able to override it with 0 or another value.
