### ISSUE TITLE
Doesn't work when input type is set

### ISSUE THREAD

**Issue by rafall** [cesarrew/ng2-currency-mask#33]
When had my input type set to 'number' my input was blank and it printed this error when I tried to write something:

`ERROR TypeError: Cannot read property 'createRange' of undefined`

Once I remove the type from the input it works.

This was my input:
`<input id="icon_prefix" type="number" currencyMask [(ngModel)]="value" [options]="{prefix: '', thousands: '.', decimal: ',', align: 'left', allowNegative: 'false' }" (change)="onUpdateAmount()" min="1">`

**Comment by cesarrew** [comment]
You can't use number as type using this directive.
