### ISSUE TITLE
Validation states such as 'touched' not applied

### ISSUE THREAD

**Issue by richyclarke** [cesarrew/ng2-currency-mask#35]
The touched property is not set to true after clicking into and out of the input element.
I'm using validation messages on the page which rely on these properties.
Any chance you could add support for this?
Thanks. Rich.

**Comment by heidermatos** [comment]
Friend I'm going through the same problem, I still have not found the solution. I'm also interested in this adjustment. I sent an email to Caesar, but there was no return.

**Comment by richyclarke** [comment]
Thanks - the other properties seem to be working ('dirty' etc.), just not 'Touched'.
Many thanks
Rich

**Comment by heidermatos** [comment]
@cesarrew muito obrigado, você irá me ajudar muito.

**Comment by RodyKirwan1** [comment]
Hi, I'm also having the same issue - "touched" property not updating on input change - which bypasses validation.
Thanks

**Comment by heidermatos** [comment]
@cesarrew Has any solution been developed for this problem?

**Comment by RodyKirwan1** [comment]
To get around this issue I had to move to "text-mask-addons"
https://www.npmjs.com/package/text-mask-addons - it is not as clean as the currency-mask, it returns a string value so you will need to convert this in @HostListener function but it works.

**Comment by cesarrew** [comment]
@richyclarke @heidermatos @RodyKirwan1 
A new version was released and should fix this issue.

**Comment by heidermatos** [comment]
Many thanks @cesarrew , I will update here on my project and test.
