### ISSUE TITLE
Add precision to non-decimal value

### ISSUE THREAD

**Issue by mikeestrada** [cesarrew/ng2-currency-mask#36]
Currently there is precision for decimals but not for integer values. Normally precision refers to the integer values and SCALE refers to the decimal values. Please add this to the options attributes. Thanks! 
:) Mike

**Comment by num13ru** [comment]
Any updates?

**Comment by mskorb** [comment]
bump

**Comment by cesarrew** [comment]
Sorry guys, but my available time to this project is very limited and I can't work on this new behavior.
