### ISSUE TITLE
Left align issue

### ISSUE THREAD

**Issue by anirudhsamudrala** [cesarrew/ng2-currency-mask#39]
I have added the options on my custom input component in angular 2 and it does not align left while other options like prefix etc., works well. Any idea?
[options]="{ align:'left' }"

**Comment by cesarrew** [comment]
@anirudhsamudrala, what version are you using?

**Comment by anirudhsamudrala** [comment]
@cesarrew  its again 1.0.1 version.

**Comment by cesarrew** [comment]
Ok. Try the latest version, which is 4.1.0. If you use Angular version 2, please use the version 2.1.0.
