### ISSUE TITLE
Update Prefix

### ISSUE THREAD

**Issue by elioth010** [cesarrew/ng2-currency-mask#4]
Its possible change the prefix with a select input ?

**Comment by cesarrew** [comment]
Can you provide a code sample about what are you trying to do?

**Comment by elioth010** [comment]
@cesarrew Sure,

```
<input currencyMask [(ngModel)]="value" [options]="options"/>

```
in the ts file i have: 

```
let options = {  prefix: '$ ', thousands: ',', decimal: '.'}

onCurrencySelect(prefix:string){
  this.options.prefix = prefix;
}

```

**Comment by cesarrew** [comment]
The new version 1.2.0 now allows setting the options attribute dynamically.
