### ISSUE TITLE
After using this i cannot use change event using angular2

### ISSUE THREAD

**Issue by somnathswami** [cesarrew/ng2-currency-mask#41]
`                <input type="text" class="form-control"currencyMask  id="perUnitPrice" required [(ngModel)]="model.perUnitPrice" name="perUnitPrice" (change)="CalculateTotalAmount(addPurchaseOrderForm.value)">`

change event is not called after change value

**Comment by cesarrew** [comment]
I will check it out. It seems that you can use (ngModelChange)="mychange($event)" as alternative.

**Comment by somnathswami** [comment]
(ngModelChange) is work for me

**Comment by hoangtri239** [comment]
native(change) trigger not working, i really need that, not (ngModelChange). How can we fix this
