### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by gmarab** [cesarrew/ng2-currency-mask#42]
Hi, 
Great directive!
Could there be no way to change management options once and for all?
Without having to repeat it for each element.
After all, when you have chosen the display options for a currency, I think it's normal that most of the elements use the same.
Thanks in advance.

**Comment by henriquecustodia** [comment]
Hello, I've create a [PR](https://github.com/cesarrew/ng2-currency-mask/pull/49) for this necessity.

**Comment by cesarrew** [comment]
Ok, I'll check it out. Thanks.

**Comment by cesarrew** [comment]
@gmarab and @henriquecustodia .This feature has been implemented and available in version 4.3.0.

**Comment by gmarab** [comment]
Thanks @cesarrew, great job!

**Comment by AbdallahBedir** [comment]
@cesarrew  But It's not available for version 2.2.0.
