### ISSUE TITLE
Dont work on samsung smarphones

### ISSUE THREAD

**Issue by filipeesch** [cesarrew/ng2-currency-mask#43]
The mask don't work in samsung phones. Tested in Galaxy S8 and Galaxy A5 using chrome and samsung stock browser.

**Comment by filipeesch** [comment]
I update the angular version and it worked.

**Comment by adrianobisca** [comment]
Hi,

What's your current angular version, i tried with the 4.2.6 and it didn't work.

Thanks in advance

**Comment by filipeesch** [comment]
I updated all packages in my project. I'm using 4.2.6 too.

**Comment by cesarrew** [comment]
@adrianobisca @filipeesch. Please try the new version 4.3.1.

**Comment by adrianobisca** [comment]
@cesarrew thank you very much, it solved the problem that my team faced in here. Cheers.
Valeu mesmo.
