### ISSUE TITLE
Can't type any number into the field on Android 6.0.1

### ISSUE THREAD

**Issue by zphingphong** [cesarrew/ng2-currency-mask#46]
As the title stated, can't type in any number on Android 6.0.1. Not sure if my pattern is wrong. It works in iOS, Chrome, Firefox and Safari, just not in Android (Chrome).

`<input currencyMask [(ngModel)]="amount" name="amount" [options]="{prefix: ''}" pattern="^[1-9]|([0-9]{1,10}\.\d{1,2})$" type="text" class="form-control" placeholder="Amount" required>`

**Comment by cesarrew** [comment]
It seems that there is a bug using this directive in Chrome in Galaxy S8. But, in your case, you used the pattern attribute. It's not necessary and I don't know if it works. Check the README.md to see how you can use this directive.

**Comment by cesarrew** [comment]
@zphingphong Please try the new version 4.3.1.
