### ISSUE TITLE
When user types in a alphabet, i get value back as 0 for my model

### ISSUE THREAD

**Issue by gpradeepjain** [cesarrew/ng2-currency-mask#50]
Hi,

I have basically 2 issues. 

My field is mandatory, so i watch for errors on field and set as error.

1. When user clears the filed value remains as 0.0
2. When user types in alphabets it return value as 0, which effects my validation as on screen we don't show any value, but error message pop ups because of validation.

**Comment by caseyPav** [comment]
+1 same issue

To the maintainers: Will pull requests be accepted on this issue? I would gladly submit one

I have the same situation along with clearing the field defaulting to 0 as opposed to the preferred null for validation reasons on a number input. 

This seems to be a common issue and would very much like to use this library but am stuck with kludges until this is resolved.

**Comment by cesarrew** [comment]
@caseyPav You can make a pull request and I will check it out as soon as possible.

**Comment by cesarrew** [comment]
Fixed in version 4.4.0.
