### ISSUE TITLE
Avoiding suffix value on ngChangeModel

### ISSUE THREAD

**Issue by ManoloPina** [cesarrew/ng2-currency-mask#52]
When a use some suffix value attribute in the suffix parameter it is applied to the value of ngModel variable incorrectly changing my ngModel variable, could I do something to avoid this ?

This is an example of my code:

`<input class="form-control default" currencyMask 
        [(ngModel)]="realtySimulation.entry"
        (ngModelChange)="onChangeSimulation('entry',$event)"
        [options]="{ prefix: 'R$ ', thousands: '.', decimal: ',', suffix: ' ('+somevalue+'%)' }"/>`

**Comment by cesarrew** [comment]
Sorry, it's not an expected usage of the attribute. I can't help you with that.
