### ISSUE TITLE
Error in version 2.x

### ISSUE THREAD

**Issue by Williammanesco** [cesarrew/ng2-currency-mask#60]
In ionic 2, install version 2.0.0 and ocurred this error in compiling

rollup failed: 'CurrencyMaskModule' is not exported by node_modules\ng2-currency-mask\index.js

Am I doing something wrong?

"npm install ng2-currency-mask@2.0.0 --save" and import module in app.module.ts

import { CurrencyMaskModule } from ng2-currency-mask

**Comment by cesarrew** [comment]
This directive is not compatible with Angular 2, if this is your case. Please use the last version of this directive (4.3.5) and Angular 4 or newer.
