### ISSUE TITLE
feature request: make decimals optional

### ISSUE THREAD

**Issue by westwick** [cesarrew/ng2-currency-mask#61]
Currently when you start typing, for example you enter "55", it will be 0.55 cents. It'd be nice to have an option to "skip" decimals for input, so the above value would be $55.00 instead.

**Comment by dhniels** [comment]
Totally agree. it would be nice to still enter decimals, perhaps flipping the order of how numbers are input perhaps? for example, if maybe somehow you could have it enter the whole number amounts by default and once a user hits decimal it captures that and enters right of the decimal and starts entering the fractional amounts. inputting tables of data can be extremely tedious when having to enter those additional digits every single row/cell

**Comment by oguzkurtcuoglu** [comment]
This is causing a lot of trouble when inputting the table row/cell. I hope will be added this feature shortly...

**Comment by cesarrew** [comment]
Sorry, it's not simple and I would need to rewrite almost all the code. The way this mask works now solve most of the situations and, unfortunately, I don't have time to recreate the component.

**Comment by westwick** [comment]
I think there is hacky ways to do it, I will open a PR :P

**Comment by westwick** [comment]
I see there is actually an open PR to address this issue. @cesarrew are you still maintaining this repo? any plans for the open PRs? would be helpful to know otherwise we will like to make a fork of this project

**Comment by cesarrew** [comment]
I'm maintaining, but my time is very limited. Today I'm going to release a new version and I hope that tomorrow I can check this PR.

**Comment by westwick** [comment]
Let me know if I can help :+1:
