### ISSUE TITLE
Can't use arrow keys, home, end in input field on Firefox (45.8.0)

### ISSUE THREAD

**Issue by jensbengtsson** [cesarrew/ng2-currency-mask#63]
Hi!

I'm using this directive in my angular app and it works great for Chrome and IE11. However in firefox I'm not able to move the cursor with the arrow keys or using home and end. So I can't do a selection of everything in the input field using shift+home or similar. 

this is with ng2-currency-mask 4.3.4
and we are using angular 4.1.3

**Comment by KatzeKahn** [comment]
Same here. Unfortunately under these circumstances, the component is not usable with Firefox.

**Comment by cesarrew** [comment]
Fixed in version 4.3.5.

**Comment by jensbengtsson** [comment]
The new release seems to point to the old commit of 4.3.4
https://github.com/cesarrew/ng2-currency-mask/commit/ab28986dae04a4c511e1110db203b6906db6f724

Was the fix really applied?

**Comment by cesarrew** [comment]
I had forgot to push the changes, but the published version is ok.

**Comment by jensbengtsson** [comment]
Thank you.

**Comment by jensbengtsson** [comment]
After we upgraded to this version we are able to enter special characters in the field which we weren't before. Was this caused by the fix?

![ng2currencymaskstuff](https://user-images.githubusercontent.com/1673887/31984243-13de317e-b961-11e7-9716-3af5478ead5a.png)

**Comment by DanielGV** [comment]
I have been working with Jens on the same problem. This seems a problem because the first cases check for the event keyCodes but the keyCode variable gets the CharCode if it is an actual character, matching the range 35-40 to #$%&‘(

I am working on a pull request to fix this and will create an issue.
