### ISSUE TITLE
Entering a number after decimal doesn't work correctly [align=left]

### ISSUE THREAD

**Issue by KatzeKahn** [cesarrew/ng2-currency-mask#64]
If the cursor is right after the decimal, entering a number does not work properly.

Example:

Current behavior:  '111,|23' => typing '9' leads to '1119,|23' what is wrong and confusing!
Correct behavior:  '111,|23' => typing '9' should lead to '111,9|2' or '111,9|23' (if more than 2 digits after comma)

**Comment by nbtai** [comment]
Because the default of `precision ` just 2, if you need more number in decimal, set the option `precision ` more than 2.

**Comment by KatzeKahn** [comment]
Nope, the issue is not about the precision. If your cursor is AFTER the decimal separator and the user types a number, it is inserted BEFORE the separator. This is because you always set the decimal position: number string length - precision. That's very confusing.

Again an example (with precision=2):
The input contains the value "12,|34" and cursor is right after the comma. Then type a 5. The input ends in "125,34". But it should be "12,53".

Another example:
Input contains "12,3|4". Cursor between 3 and 4. Typing a 5 ends in "123,54" but should be "12,35".


**Probably, the current behavior works for right aligned numbers but NOT for **left** aligned ones. Here, we need another behavior like described above. Otherwise users will go crazy when entering data.**

**Comment by cesarrew** [comment]
I understand what you are saying, but this requiment is different from what most of masks do. I also don't agree with this behavior, because in your example (The input ends in "125,34". But it should be "12,53") the last digit will be lost.
Besides, you are the first one with this need, so I can't do this change.

**Comment by KatzeKahn** [comment]
I understand your arguments with regards to currencies. I tried to use your component as input for arbitrary numbers since there is no suitable solution on the market. Eventually, it seems that I have to write my own one to make it working. Thanks, anyway. :)

**Comment by nbtai** [comment]
@KatzeKahn Can you share it for me too, I am still stucking in this issue :(
