### ISSUE TITLE
Question: Defaulting to numeric keyboard on a mobile device

### ISSUE THREAD

**Issue by OneHP** [cesarrew/ng2-currency-mask#65]
Hi,

I'm using the mask on an input field for which I would like to have the numeric keyboard pop-up when the user is on a mobile device. It seems like the only way to have that keyboard be the default is to set `type="number"` but this obviously stops the mask working as it depends on the input being of type `text`.

I wondered if you had tried to tackle anything like this before? Or whether you would be able to support `type="number"`?

Thanks

**Comment by cesarrew** [comment]
Hi. I had not. Sorry, there isn't an easy way doing that.
