### ISSUE TITLE
Character codes match arrow KeyCodes

### ISSUE THREAD

**Issue by DanielGV** [cesarrew/ng2-currency-mask#66]
As a consequence to #63 some character codes #$%&'( match the keycodes for arrows.
The cases for keyCodes should be done apart from the charCodes (similar problems might occur with the correspondent keyCode equivalent to +-).

**Comment by cesarrew** [comment]
@DanielGV Thanks for your PR, but I needed to change some lines. The new version 4.4.1 fixed this issue.
