### ISSUE TITLE
Can not delete input content. "$ 0" instead of placeholder

### ISSUE THREAD

**Issue by ge0rgecz** [cesarrew/ng2-currency-mask#69]
situation:
1. empty input shows only placeholder
2. type in number
3. then select using ctrl+a and press DELETE or BACKSPACE
4. **value changes to $ 0 instead of empty input showing placeholder only** <-- bug ?

**Comment by ruonan59** [comment]
same question for bullet 4, 
how to delete a value and leave it as empty, instead of "0"?

**Comment by ruonan59** [comment]
i created a keyup event that manually set the filed to empty if the key pressed is backspace or delete, and the input value is '$0.00', which resolved the issue.

**Comment by ruonan59** [comment]
issue resolved. just update to the latest version. no need for the keyup event.

**Comment by cesarrew** [comment]
It's working in newest version.
