### ISSUE TITLE
Will it work for Angular 5?

### ISSUE THREAD

**Issue by sa582** [cesarrew/ng2-currency-mask#73]
Hello ,
I am creating an application with angular 5. As you mentioned use version 4.4.1 for angular 4 will it work for angular 5 as well or do we need to wait until new version released?

**Comment by cesarrew** [comment]
I didn't have time to test, but I didn't see any change in Angular 5 that would create problems.

**Comment by arcarruda** [comment]
I've tested and I already found a little bug.
```
ERROR TypeError: this.onModelChange is not a function
Stack trace:
InputHandler.prototype.handleKeypress@webpack-internal:///../../../../ng2-currency-mask/src/input.handler.js:85:9
```
To fix I have changed the line 85 to:
`
        if(this.onModelChange)
            this.onModelChange(this.inputService.value);
`

**Comment by jasonhjohnson** [comment]
I have this issue as well; would obviously prefer not changing the source.

**Comment by cesarrew** [comment]
It was tested and no problems were founded in latest version when using with Angular 5.

**Comment by tolgabalci** [comment]
I'm having the same issue:

> SizingAndSelectComponent.html:61 ERROR TypeError: this.onModelChange is not a function
>     at InputHandler.handleKeypress (input.handler.js:110)
>     at CurrencyMaskDirective.handleKeypress (currency-mask.directive.js:67)
>     at Object.eval [as handleEvent] (SizingAndSelectComponent.html:61)
>     at handleEvent (core.js:13581)
>     at callWithDebugContext (core.js:15090)
>     at Object.debugHandleEvent [as handleEvent] (core.js:14677)
>     at dispatchEvent (core.js:9990)
>     at eval (core.js:10611)
>     at HTMLInputElement.eval (platform-browser.js:2628)
>     at ZoneDelegate.invokeTask (zone.js:421)

All I did was npm install, make the necessary changes to the app.module.ts and add this to my html (plus create a variable in the component called myNumber: string)

`<input currencyMask [(ngModel)]="myNumber" min="-10.50" max="100.75" />`

**Comment by alexandre-pereira** [comment]
Same issue (ionic 3 & angular 5)

**Comment by victordev** [comment]
Same issue (angular 5.2.0, ng2-currency-mask 5.3.1)

**Comment by dazdylz** [comment]
same problem here. angular 5, ionic 3

**Comment by GezzMan** [comment]
You should reopen this issue because we can't use directive if our inputs don't have NgModel

**Comment by mylesjj** [comment]
Any news on this

**Comment by rafaelgoncalves2010** [comment]
same problem here, HOW TO FIX IT???

**Comment by zr87** [comment]
> ERROR TypeError: this.onModelChange is not a function
It throws this error because the input wants to inform the form that the input itself has changed.

The currency-mask directive implements ControlValueAccessor interface which means: if you add the the directive to whatever element then it needs to be a part of a form: "template driven"  or "reactive"... In case of template driven, it is obligatory to add a ngModel or 'formControlName' attribute in case of a reactive form to be 100% compatible.

This is not explicitly mentioned and it would helpful to clear up the usage of this directive.
