### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by nutwiss** [cesarrew/ng2-currency-mask#74]
I cannot use the [options] property of an <input> control to configure the ng2-currency-mask component.

The error "Can't bind to 'options' since it isn't a known property of 'input'" is thrown.

The ng2-currency-mask (v4.4.1) package installed correctly and the CurrencyMaskModule has been imported into my module.

Can you suggest any potential fix for this, please?

Thanks

**Comment by nutwiss** [comment]
I had to explicitly import 'CurrencyMaskDirective' into my component, and move my module import down a level (we have a multi-level module hierarchy).

**Comment by nutwiss** [comment]
Also is there a way to not default the input box to '£0' for example? This is wiping out my input box placeholder text.

**Comment by cesarrew** [comment]
Hi. Are you having this problem yet? I recreated the project with angular-cli and it's working with no errors.

**Comment by Qleoz12** [comment]
> CurrencyMaskDirective

Its is falling for me alse
