### ISSUE TITLE
Add numbers from left to right

### ISSUE THREAD

**Issue by Sliqric7053** [cesarrew/ng2-currency-mask#76]
Hi there

I would like to know if there's an option (or workaround) to get the numbers added from left to right.

Example:
At the moment when I type `1234` the output for each digit is [`0.01`] [`0.12`] [`1.23`] [`12.34`] respectively.
I would like it to output [`1234.00`]

Any pointers would be highly appreciated.

Thanks

**Comment by patrickoneill46** [comment]
Yes, this would be a nice feature. A quick look at the source - a boolean flag could accomplish this (I think)

**Comment by Sliqric7053** [comment]
@patrickoneill46 Have a look at this https://github.com/cesarrew/ng2-currency-mask/issues/61 I think if it was that simple "they" would have done the change a long time ago..

Perhaps give it a try :)

**Comment by cesarrew** [comment]
Sorry, it's not simple and I would need to rewrite almost all the code. The way this mask works now solve most of the situations and, unfortunately, I don't have time to recreate the component.
