### ISSUE TITLE
Incorrect digit position entry when all digits selected before input

### ISSUE THREAD

**Issue by dexster** [cesarrew/ng2-currency-mask#77]
Issue when using this config:
    allowNegative: false,
    allowZero: true,
    decimal: '.',
    precision: 2,

If all input is selected and a digit is entered then the digit is inserted in the wrong position eg.
0.00 is in the input field. You select everything then press 1. The result is 0.10 when the expected result is 0.01.

Adding the first selectionRange check below to the handleKeydown event seems to fix it. I can submit a pull request but not sure if this fix is the best way.

```javascript
    handleKeydown(event: any): void {
        let keyCode = event.which || event.charCode || event.keyCode;
        let selectionRangeLength = Math.abs(this.inputService.inputSelection.selectionEnd - this.inputService.inputSelection.selectionStart);

        if (selectionRangeLength == this.inputService.rawValue.length) {
            this.setValue(null);
            this.onModelChange(this.inputService.value);
        }
        if (keyCode == 8 || keyCode == 46 || keyCode == 63272) {
```

**Comment by cesarrew** [comment]
Fixed in lastest version.
