### ISSUE TITLE
Not Format options - ngModel does not work

### ISSUE THREAD

**Issue by lduarteoliveira** [cesarrew/ng2-currency-mask#78]
Hi,

When declare:

            <input 
            class="form-control" 
            currencyMask 
            [options]="{ prefix: '', thousands: '.', decimal: ',' }"
            [value]="curso.ValorAnuidade"
            [(ngModel)]="curso.ValorAnuidade"
            name="ValorAnuidade"
            #ValorAnuidade="ngModel"
            maxlength="10"
            [value]="curso.ValorAnuidade"
            placeholder="0,00"
            required />

The options does not work. The mask is: 999999.99. When must have been 999.999,99.

If I take  #ValorAnuidade="ngModel", it does work.

Best regards!

**Comment by cesarrew** [comment]
Hi. It seems that you are not using the component as it supposed to be. Please check the documentation in https://www.npmjs.com/package/ng2-currency-mask.

**Comment by cesarrew** [comment]
Minimum and maximum values validation are now available in version 5.3.0.
