### ISSUE TITLE
<input readonly> property doesn't work

### ISSUE THREAD

**Issue by kinlhp** [cesarrew/ng2-currency-mask#81]
I have an input that, at a certain point, should be read only. But, by using the `currencyMask` directive in an `<input readonly>` element, the behavior is not as expected. Apparently everything seems OK because the hover event does not visually alter the element, however when you click on it and start typing the error occurs. Here is an example I used here: 

`<!-- valor -->`
`<div class="ui-g-12 ui-md-6 ui-fluid">`
`    <label for="inputValor" id="labelValor">Valor unitário</label>`
`    <input id="inputValor" name="inputValor" type="text" currencyMask pInputText required [options]="{allowNegative: false, decimal: ',', prefix: 'R$ ', thousands: '.'}" readonly [(ngModel)]="alteracoes.produto.valor">`
`</div>`

**Comment by jasonbrandt42** [comment]
I also have an error with the input readonly state.   When in readonly state = it allows editing.

**Comment by nerk** [comment]
A fix would be to add 

```
if (this.htmlInputElement && this.htmlInputElement.readOnly) {
    return;
}
```

to the top of each of the  `handleXXX` methods in input.handler.ts.

**Comment by jasonbrandt42** [comment]
This appears to have worked fine for me as a solution.

**Comment by tiagoa** [comment]
I did otherwise: https://github.com/tiagoa/ng2-currency-mask/commit/f00dac415dd6198206b22e5b166709e1a4423b48

**Comment by nerk** [comment]
I did not try your solution, but will this also prevent from pasting from the clipboard (handlePaste())?

**Comment by cesarrew** [comment]
Fixed in newest version.
