### ISSUE TITLE
Is there a way to use decimals with the percent formatter?

### ISSUE THREAD

**Issue by pscanlon1** [cesarrew/ng2-currency-mask#84]
How would you suggest to use this for percent formatting...

ie.. user types in 10
you show 10%

model value is .1

Thanks!

**Comment by cesarrew** [comment]
Hi. This is not the goal of this component. Maybe you can find this behaviour in a component in PrimeNG.

**Comment by cesarrew** [comment]
Sorry for my mistake. You already can do this using as follow:

<input currencyMask [(ngModel)]="value" [options]="{ prefix: '', suffix: '%', precision: '0' }" />
