### ISSUE TITLE
Request Feature: Include 'postfix' option

### ISSUE THREAD

**Issue by baldonharris** [cesarrew/ng2-currency-mask#88]
Can 'postfix' be added as an option? I mean, we can use this plugin for percentage input also; not just for currency masking.

`<input type="text" currencyMask [options]="{ postfix: '%', align: 'left'}" value="2">`

Would output:

"2.00%"

**Comment by cesarrew** [comment]
You already can do this using in this way:

`<input currencyMask [(ngModel)]="value" [options]="{ prefix: '', suffix: '%', thousands: '.', decimal: ',' }"`
