### ISSUE TITLE
minlength property doesn't play nice with currencyMask

### ISSUE THREAD

**Issue by ryanbuening** [cesarrew/ng2-currency-mask#90]
If you set `currencyMask` and a `minlength` property on an input, `ng-invalid` does not seem to get set consistently.

I'm using Angular v5.

**Comment by cesarrew** [comment]
It's because the text in the input is converted to a number. This way, the minlength validator doesn't make sense.

**Comment by cesarrew** [comment]
Minimum and maximum values validation are now available in version 5.3.0.
