### ISSUE TITLE
Input giving NaN in Ionic 3 and Angular 4

### ISSUE THREAD

**Issue by luciojb** [cesarrew/ng2-currency-mask#91]
Hello!

I'm grateful there is this amazing mask. The only issue so far, is that when deleting all content in the input box, the model will be set to NaN. I'm using Ionic version 3 and Angular 4, and followed the instructions for ionic already. I managed to work around with a validation in the ts file of the page, but it's an unnecessary code, so it would be great to give it a look.

The settings are all the default ones, and the environment the same as others. The only things different are that i'm using just input instead of ion-input, although it may not be the issue, and align left.

Best regards.

**Comment by luciojb** [comment]
Update: the settings are global and the following:

`align: "left",
 allowNegative: false,
 allowZero: true,
 decimal: ",",
 precision: 2,
 prefix: "R$ ",
 suffix: "",
 thousands: "."`

**Comment by ifdouglas** [comment]
I have the same issue, but i'm not using Ionic and my Angular version is 5.

**Comment by carlosmorcerf** [comment]
try this while fixing the bug....

this.form.controls["controlName"].valueChanges.subscribe((val) => {
      if (String(val)==="NaN"){
        this.form.controls["controlName"].setValue(null);
      }
});

**Comment by luciojb** [comment]
@carlosmorcerf thanks, it worked right. For now, I'm applying this to fix the issue. I still not knowing if this affects other kind of environments.

**Comment by daverickdunn** [comment]
This also causes flies in the face of with Angular's most basic Validator, `required`.

See source and spot the problem:

```
function isEmptyInputValue(value: any): boolean {
  // we don't check for string here so it also works with arrays
  return value == null || value.length === 0;
}
```
```
  static required(control: AbstractControl): ValidationErrors|null {
    return isEmptyInputValue(control.value) ? {'required': true} : null;
  }
```

In turn, it also _effectively_ breaks Validators `min` and `max`.

**Comment by cesarrew** [comment]
Fixed in newest version.
