### ISSUE TITLE
Critical issue with decimal precision

### ISSUE THREAD

**Issue by RenjithPr90** [cesarrew/ng2-currency-mask#93]
My requirement is to have a precision of two. But when i type any number, first decimal value is filled.
eg: if i type 54 then it shows like **0.54** instead of **54.00,** if i type **545** it appears as **5.45** instead of **545.00**

My suggestion is user should be able to input dot at their wish. Also need to have limit for max number to be entered

**Comment by msaqib09** [comment]
Facing the same issue. Its behavior should not work like this.

**Comment by cesarrew** [comment]
Hi. It's not an issue. Your requirement is different from how this mask works.

**Comment by msaqib09** [comment]
Hi , Can you provide the solution according to my requirement. Because  I have tried the solution it is not working.

**Comment by RenjithPr90** [comment]
@cesarrew  I think this is an issue. Basically if i type 54 then it should come as 54.00 and not 0.54 and if i try 444 it should come as 444.00 not as 4.44.

**Comment by kamilklosowski** [comment]
@cesarrew i also think that this may be the issue. And it cannot be omitted - f.ex. setting precision to 0 disallow me to type decimal separator and decimals by myself.

**Comment by elessariel** [comment]
I as well would like to see a solution to this.

**Comment by pradeepgururani** [comment]
This behaviour should be configurable.

**Comment by pradeepgururani** [comment]
@ge0rgecz have you found any alternative to this component? I will also drop this component if anything better is out there.

**Comment by elessariel** [comment]
@ge0rgecz  I would also be interested in an alternative component due to this issue which seems to stick.

**Comment by ge0rgecz** [comment]
Alternative for this component is standard CurrencyPipe from @angular/common. You can use this pipe on input field value too. Its good enough for my purposes. https://stackoverflow.com/questions/48321610/angular-4-how-to-use-currency-pipe-in-input-type

**Comment by Swad** [comment]
The precision setting needs work? Anyone was able to get around this problem?

The text-mask plugin suggested above does not have auto unmasking. You will have to manually unmask each input element, which is not a great option.

https://github.com/text-mask/text-mask/tree/master/angular2#unmasking-the-value-that-is-stored-in-the-model
https://github.com/text-mask/text-mask/issues/109

**Comment by egaviriarestrepo** [comment]
Did someone solve it?

**Comment by ajaygangarde** [comment]
> My requirement is to have a precision of two. But when i type any number, first decimal value is filled.
> eg: if i type 54 then it shows like **0.54** instead of **54.00,** if i type **545** it appears as **5.45** instead of **545.00**
> 
> My suggestion is user should be able to input dot at their wish. Also need to have limit for max number to be entered

Please Anyone Got solution for above raised point..

**Comment by ajaygangarde** [comment]
We need two files as below directive and pipe 

DIRECTIVE  - my-currency-formatter.directive.ts
Pipe - my-currency.pipe.ts




import { Directive, HostListener, ElementRef, OnInit, Input, Renderer2, forwardRef } from '@angular/core';
import { MyCurrencyPipe } from '../pipes/my-currency.pipe';
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';
const noop = () => { };

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => MyCurrencyDirective),
    multi: true
};

@Directive({
    selector: '[MyCurrencyFormatter]',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})
export class MyCurrencyDirective implements OnInit, ControlValueAccessor {
    private el: HTMLInputElement;
    // Keeps track of the value without formatting
    private innerValue: any;
    // Optional Parameter to allow for negative number interaction
    @Input('allowNegative') allowNegative: boolean;
    @Input('prefix') public prefix: any;
    @Input('fractionSize') public fractionSize: any;
    keyDownCount: number = 0;

    constructor(
        private elementRef: ElementRef,
        private renderer: Renderer2,
        private formatcurrencypipe: MyCurrencyPipe,
    ) {
        this.el = this.elementRef.nativeElement;
    }

    // Placeholders for the callbacks which are later providesd
    // by the Control Value Accessor
    private onTouchedCallback: () => void = noop;
    private onChangeCallback: (a: any) => void = noop;

    // set getter
    get value(): any {
        return this.innerValue;
    }

    // set accessor including call the onchange callback
    set value(v: any) {
        if (v !== this.innerValue) {
            this.innerValue = v;
            this.onChangeCallback(v);
        }
    }

    // From ControlValueAccessor interface
    writeValue(value: any) {
        if (value !== this.innerValue) {
            this.el.value = this.formatcurrencypipe.transform(value, this.fractionSize, this.prefix);
            this.innerValue = value;
        }
    }

    // From ControlValueAccessor interface
    registerOnChange(fn: any) {
        this.onChangeCallback = fn;
    }

    // From ControlValueAccessor interface
    registerOnTouched(fn: any) {
        this.onTouchedCallback = fn;
    }

    // On Focus remove all non-digit or decimal separator values
    @HostListener('focus', ['$event.target.value'])
    onfocus(value) {
        this.el.value = this.formatcurrencypipe.transform(this.el.value, this.fractionSize, this.prefix);
        this.el.value = this.formatcurrencypipe.parse(value, this.fractionSize, this.prefix);
    }

    // // On Blue remove all symbols except last . and set to currency format
    @HostListener('blur', ['$event.target.value'])
    onblur(value) {
        this.onTouchedCallback();
        this.el.value = this.formatcurrencypipe.transform(this.el.value, this.fractionSize, this.prefix);
        this.onChangeCallback(this.formatcurrencypipe.parse(this.el.value, this.fractionSize, this.prefix));
    }


    ngOnInit() {
        // this.el.value = this.formatcurrencypipe.parse(this.el.value, this.fractionSize, this.prefix);
        this.onChangeCallback(this.formatcurrencypipe.parse(this.el.value, this.fractionSize, this.prefix));
    }

    @HostListener('keyup', ['$event']) onkeyup(event) {
        this.onChangeCallback(this.formatcurrencypipe.parse(event.target.value, this.fractionSize, this.prefix));
        this.keyUp();
    }

    keyUp() {
        let e = <KeyboardEvent>event;
        if ([46, 8, 9, 27, 13, 110, 190].indexOf(e.keyCode) !== -1 ||
            // Allow: Ctrl+A
            (e.keyCode === 65 && (e.ctrlKey || e.metaKey)) ||
            // Allow: Ctrl+C
            (e.keyCode === 67 && (e.ctrlKey || e.metaKey)) ||
            // Allow: Ctrl+V
            (e.keyCode === 86 && (e.ctrlKey || e.metaKey)) ||
            // Allow: Ctrl+X
            (e.keyCode === 88 && (e.ctrlKey || e.metaKey)) ||
            // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
            // let it happen, don't do anything
            return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();

        }
    }

}


my-currency.pipe.ts


import { Pipe, PipeTransform } from '@angular/core';
const padding = "000000";

@Pipe({
  name: 'myCurrency'
})
export class MyCurrencyPipe implements PipeTransform {
  // private prefix: string;
  private decimal_separator: string;
  private thousands_separator: string;
  private suffix: string;

  constructor() {
    // this.prefix='';
    this.suffix = '';
    this.decimal_separator = '.';
    this.thousands_separator = ',';
  }
  
  transform(value: string, fractionSize: number = 2, prefix: string = ''): string {

    if (parseFloat(value) % 1 != 0) {
      fractionSize = 2;
    }
    let [integer, fraction = ""] = (parseFloat(value).toString() || "").toString().split(".");

    fraction = fractionSize > 0
      ? this.decimal_separator + (fraction + padding).substring(0, fractionSize) : "";
    integer = integer.replace(/\B(?=(\d{3})+(?!\d))/g, this.thousands_separator);
    if (isNaN(parseFloat(integer))) {
      integer = "0";
    }
    return prefix + integer + fraction + this.suffix;

  }

  parse(value: string, fractionSize: number = 2, prefix: string = ''): string {
    let [integer, fraction = ""] = (value || "").replace(prefix, "")
      .replace(this.suffix, "")
      .split(this.decimal_separator);

    integer = integer.replace(new RegExp(this.thousands_separator, "g"), "");

    fraction = parseInt(fraction, 10) > 0 && fractionSize > 0
      ? this.decimal_separator + (fraction + padding).substring(0, fractionSize)
      : "";

    return integer + fraction;
  }

}

In TEMPLATE we can use as 

<input type="text"  **MyCurrencyFormatter fractionSize="2" prefix="$"**   />

**Comment by ajaygangarde** [comment]
We need two files as below directive and pipe

DIRECTIVE - my-currency-formatter.directive.ts
Pipe - my-currency.pipe.ts
```

import { Directive, HostListener, ElementRef, OnInit, Input, Renderer2, forwardRef } from '@angular/core';
import { MyCurrencyPipe } from '../pipes/my-currency.pipe';
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';
const noop = () => { };

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
provide: NG_VALUE_ACCESSOR,
useExisting: forwardRef(() => MyCurrencyDirective),
multi: true
};

@directive({
selector: '[MyCurrencyFormatter]',
providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})
export class MyCurrencyDirective implements OnInit, ControlValueAccessor {
private el: HTMLInputElement;
// Keeps track of the value without formatting
private innerValue: any;
// Optional Parameter to allow for negative number interaction
@input('allowNegative') allowNegative: boolean;
@input('prefix') public prefix: any;
@input('fractionSize') public fractionSize: any;
keyDownCount: number = 0;

constructor(
    private elementRef: ElementRef,
    private renderer: Renderer2,
    private formatcurrencypipe: MyCurrencyPipe,
) {
    this.el = this.elementRef.nativeElement;
}

// Placeholders for the callbacks which are later providesd
// by the Control Value Accessor
private onTouchedCallback: () => void = noop;
private onChangeCallback: (a: any) => void = noop;

// set getter
get value(): any {
    return this.innerValue;
}

// set accessor including call the onchange callback
set value(v: any) {
    if (v !== this.innerValue) {
        this.innerValue = v;
        this.onChangeCallback(v);
    }
}

// From ControlValueAccessor interface
writeValue(value: any) {
    if (value !== this.innerValue) {
        this.el.value = this.formatcurrencypipe.transform(value, this.fractionSize, this.prefix);
        this.innerValue = value;
    }
}

// From ControlValueAccessor interface
registerOnChange(fn: any) {
    this.onChangeCallback = fn;
}

// From ControlValueAccessor interface
registerOnTouched(fn: any) {
    this.onTouchedCallback = fn;
}

// On Focus remove all non-digit or decimal separator values
@HostListener('focus', ['$event.target.value'])
onfocus(value) {
    this.el.value = this.formatcurrencypipe.transform(this.el.value, this.fractionSize, this.prefix);
    this.el.value = this.formatcurrencypipe.parse(value, this.fractionSize, this.prefix);
}

// // On Blue remove all symbols except last . and set to currency format
@HostListener('blur', ['$event.target.value'])
onblur(value) {
    this.onTouchedCallback();
    this.el.value = this.formatcurrencypipe.transform(this.el.value, this.fractionSize, this.prefix);
    this.onChangeCallback(this.formatcurrencypipe.parse(this.el.value, this.fractionSize, this.prefix));
}


ngOnInit() {
    // this.el.value = this.formatcurrencypipe.parse(this.el.value, this.fractionSize, this.prefix);
    this.onChangeCallback(this.formatcurrencypipe.parse(this.el.value, this.fractionSize, this.prefix));
}

@HostListener('keyup', ['$event']) onkeyup(event) {
    this.onChangeCallback(this.formatcurrencypipe.parse(event.target.value, this.fractionSize, this.prefix));
    this.keyUp();
}

keyUp() {
    let e = <KeyboardEvent>event;
    if ([46, 8, 9, 27, 13, 110, 190].indexOf(e.keyCode) !== -1 ||
        // Allow: Ctrl+A
        (e.keyCode === 65 && (e.ctrlKey || e.metaKey)) ||
        // Allow: Ctrl+C
        (e.keyCode === 67 && (e.ctrlKey || e.metaKey)) ||
        // Allow: Ctrl+V
        (e.keyCode === 86 && (e.ctrlKey || e.metaKey)) ||
        // Allow: Ctrl+X
        (e.keyCode === 88 && (e.ctrlKey || e.metaKey)) ||
        // Allow: home, end, left, right
        (e.keyCode >= 35 && e.keyCode <= 39)) {
        // let it happen, don't do anything
        return;
    }
    // Ensure that it is a number and stop the keypress
    if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
        e.preventDefault();

    }
}
}
```

my-currency.pipe.ts

```
import { Pipe, PipeTransform } from '@angular/core';
const padding = "000000";

@pipe({
name: 'myCurrency'
})
export class MyCurrencyPipe implements PipeTransform {
// private prefix: string;
private decimal_separator: string;
private thousands_separator: string;
private suffix: string;

constructor() {
// this.prefix='';
this.suffix = '';
this.decimal_separator = '.';
this.thousands_separator = ',';
}

transform(value: string, fractionSize: number = 2, prefix: string = ''): string {

if (parseFloat(value) % 1 != 0) {
  fractionSize = 2;
}
let [integer, fraction = ""] = (parseFloat(value).toString() || "").toString().split(".");

fraction = fractionSize > 0
  ? this.decimal_separator + (fraction + padding).substring(0, fractionSize) : "";
integer = integer.replace(/\B(?=(\d{3})+(?!\d))/g, this.thousands_separator);
if (isNaN(parseFloat(integer))) {
  integer = "0";
}
return prefix + integer + fraction + this.suffix;
}

parse(value: string, fractionSize: number = 2, prefix: string = ''): string {
let [integer, fraction = ""] = (value || "").replace(prefix, "")
.replace(this.suffix, "")
.split(this.decimal_separator);

integer = integer.replace(new RegExp(this.thousands_separator, "g"), "");

fraction = parseInt(fraction, 10) > 0 && fractionSize > 0
  ? this.decimal_separator + (fraction + padding).substring(0, fractionSize)
  : "";

return integer + fraction;
}

}
```

In TEMPLATE we can use as

<input type="text" MyCurrencyFormatter fractionSize="2" prefix="$" />

**Comment by pcbl** [comment]
> My requirement is to have a precision of two. But when i type any number, first decimal value is filled.
> eg: if i type 54 then it shows like **0.54** instead of **54.00,** if i type **545** it appears as **5.45** instead of **545.00**
> 
> My suggestion is user should be able to input dot at their wish. Also need to have limit for max number to be entered

Same situation happened with a customer... They got annoyed with this behavior. Would be nice if we have this behavior configurable, as suggested above.

**Comment by pcbl** [comment]
Hi Folks,

While we do not have an alternative from the component self, I added the custom behavior on the way it suit my needs. Maybe that would help someone:
Basically I created two event handlers:
`
  public currencyMaskFocus($event)
  {        
    //getting current value
    var value =  $event.currentTarget.value;
    //splitting by the value by the decimal separator
    var splitted = value.split(this.currencyFormatInfo.decimal);
    //selecting the integer part, which will be replaced with what the user will type
    //For example: 100,82 - where , is the decimal separator
    //We would select 100
    $event.currentTarget.selectionStart=0;
    $event.currentTarget.selectionEnd=splitted[0].length;    
  }

  public currencyMastKeydown($event)
  {
    //When the user presses ,
    //We want to select the decimal part to allow editting only the decimal part
    if($event.key==',')
    {
      //First of all, we cancel all event propagation and the default behavior!
      $event.stopPropagation();
      $event.preventDefault();
      //Then we get the value itself
      var value =  $event.currentTarget.value;
      //Find out where the decimal separator ist
      var start = value.indexOf(this.currencyFormatInfo.decimal)+1;    
      //select only the decimal part
      //For example: 100,82 - where , is the decimal separator
      //Would select only 82
      $event.currentTarget.selectionStart=start;
      $event.currentTarget.selectionEnd=start+this.currencyFormatInfo.precision;    
    }  
  }
`

As I am using the global configuration(CURRENCY_MASK_CONFIG), the currencyFormatInfo variable was injected like this via my class constructor:
`constructor(@Inject(CURRENCY_MASK_CONFIG) private currencyFormatInfo: CurrencyMaskConfig) { }`

Last but not least, I added the handlers on my input which holds the currencyMask directive:
<input type="text" currencyMask  (focus)="currencyMaskFocus($event)" (keydown)="currencyMastKeydown($event)" >`
`
I know this solution is a bit "quick and dirty" but it solved this specific need.

Thanks and keep up the great work!

BR
Pedro

**Comment by jimkeecn** [comment]
@pcbl  Hi, I have tried with your solution but I got an error 
![image](https://user-images.githubusercontent.com/19795378/52393395-f5c40b80-2af9-11e9-9fb8-fd425c580bf8.png)
btw, I am using angular 7 for my project.

**Comment by pilouk** [comment]
I also think this is an issue

**Comment by Vijay-Tummala** [comment]
I am facing issue too. Customer treats this as a bug.

**Comment by grmkris** [comment]
same here sadly :( stupid customers

**Comment by G3Kappa** [comment]
+1. A client has been complaining about the default behaviour, and it seems silly that this library still does not support a normal input mode either by default or through configuration. Nobody starts typing numbers from the right; in fact, everyone I know starts typing numbers from the left.

**Comment by ajaygangarde** [comment]
I have custom directive for this. We also went throught this issues.

**Comment by shyntaayu** [comment]
> Hi. It's not an issue. Your requirement is different from how this mask works.

so, how to fix it
can you give me example?

**Comment by cesarrew** [comment]
Sorry guys, but my available time to this project is very limited and I can't work on this new behavior.

**Comment by andy6174** [comment]
> My requirement is to have a precision of two. But when i type any number, first decimal value is filled. eg: if i type 54 then it shows like **0.54** instead of **54.00,** if i type **545** it appears as **5.45** instead of **545.00**
> 
> My suggestion is user should be able to input dot at their wish. Also need to have limit for max number to be entered

Any solution of this issue
